export const Images = {
  Arrow: require('assets/images/arrow.png'),
  Search: require('assets/images/search.png'),
  Offer: require('assets/images/offer.png'),
  Learn: require('assets/images/learn.png'),
  Find: require('assets/images/find.png'),
  VideoPoster: require('assets/images/video-poster.png'),
  Logo: require('assets/images/logo.png'),
  Direction: require('assets/images/map.png'),
  Facebook: require('assets/images/facebook.svg').default,
  Google: require('assets/images/google.svg').default,
  Apple: require('assets/images/apple-logo.svg').default,
  Home: require('assets/images/home.svg').default,
  Latest: require('assets/images/latest.svg').default,
  Offers: require('assets/images/offers.svg').default,
  User: require('assets/images/user.svg').default,
  PostLogo: require('assets/images/post-logo.svg').default,
  Heart: require('assets/images/heart.svg').default,
  Smile: require('assets/images/smile-plus.svg').default,
  LogoMain: require('assets/images/logo.svg').default,
  BusinessMarker: require('assets/images/business-marker.png'),
  EmptyState: require('assets/images/empty-state.svg').default,
  Email: require('assets/images/email.svg').default,
  WelcomeBackground: require('assets/images/welcome-background.png'),
  WelcomeInfo: require('assets/images/welcome-info.svg').default,
  WelcomeLogo: require('assets/images/welcome-logo.svg').default,
};
